# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hospitalQueuePatientScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as connector

class hospitalQueuePatientScreenUiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(865, 287)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.sendButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.patientNameLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patientNameLineEdit.sizePolicy().hasHeightForWidth())
        self.patientNameLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.patientNameLineEdit.setFont(font)
        self.patientNameLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.patientNameLineEdit.setObjectName("patientNameLineEdit")
        self.verticalLayout_2.addWidget(self.patientNameLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.docNameLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.docNameLineEdit.sizePolicy().hasHeightForWidth())
        self.docNameLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.docNameLineEdit.setFont(font)
        self.docNameLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.docNameLineEdit.setObjectName("docNameLineEdit")
        self.verticalLayout_3.addWidget(self.docNameLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.clinicNameLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clinicNameLineEdit.sizePolicy().hasHeightForWidth())
        self.clinicNameLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.clinicNameLineEdit.setFont(font)
        self.clinicNameLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.clinicNameLineEdit.setObjectName("clinicNameLineEdit")
        self.verticalLayout_4.addWidget(self.clinicNameLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 2, 0, 1, 1)
        
        self.hospitalQueueDatabaseConnection = connector.connect(
            host = "localhost",
            user = "Emirhan Ak",
            password = "Ak004755590*",
            database = "hospitalQueueDatabase"
            )
        
        self.connectionCursor = self.hospitalQueueDatabaseConnection.cursor()
        
        self.connectionCursor.execute("SELECT * FROM patientInfo")
        try:
            self.patientNo = self.connectionCursor.fetchall()[-1][0] + 1
        except:
            self.patientNo = 1
        self.sendButton.clicked.connect(self.sendDataToSQL)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def sendDataToSQL(self):
        insertPatientInfoOperation = "INSERT INTO patientInfo (patientNo, patientName, doctorName, clinicName) VALUES (%s, %s, %s, %s)"
        self.connectionCursor.execute(insertPatientInfoOperation, (str(self.patientNo), self.patientNameLineEdit.text().upper(), self.docNameLineEdit.text().upper(), self.clinicNameLineEdit.text().upper()))
        self.hospitalQueueDatabaseConnection.commit()
        self.patientNo += 1
        
        self.patientNameLineEdit.setText("")
        self.docNameLineEdit.setText("")
        self.clinicNameLineEdit.setText("")
        self.statusLabel.setText("Sıranız ayrıldı.")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hastane Sıra Kontrol Sistemi Kullanıcı Ekranı"))
        self.sendButton.setText(_translate("Form", "GÖNDER"))
        self.label_2.setText(_translate("Form", "HASTA ADI"))
        self.label.setText(_translate("Form", "HEKİM ADI"))
        self.label_4.setText(_translate("Form", "BÖLÜM ADI"))
        self.statusLabel.setText(_translate("Form", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = hospitalQueuePatientScreenUiForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
